=== Jorghy/QOHYCR_XMLgyak/QOHYCR_0924/iskola.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT iskola (tanar+, tantargy+)>
<!ELEMENT tanar (nev?, szak?)>
<!ATTLIST tanar kod ID #REQUIRED>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ELEMENT targy (tnev?, osztaly?)>
<!ATTLIST targy kod ID #REQUIRED>
<!ATTLIST targy oktato IDREF #IMPLIED>
<!ELEMENT tnev (#PCDATA)>
<!ELEMENT osztaly (#PCDATA)>

=== Jorghy/QOHYCR_XMLgyak/QOHYCR_0924/iskola.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE note SYSTEM "iskola.dtd">

<iskola>
	<tanar kod="tan_01">
		<nev>Kiss Béla</nev>
		<szak>Informatika</szak>
	</tanar>
	<targy kod="tr_01" oktato="tan_01">
		<tnev>Számítástechnika alapok</tnev>
		<osztaly>Harmadik</osztaly>
	</targy>
	<tanar kod="tan_02">
		<nev>Árva Ibolya</nev>
		<szak>Biológia</szak>
	</tanar>
	<targy kod="tr_02" oktato="tan_02">
		<tnev>Biológia</tnev>
		<osztaly>Ötödik</osztaly>
	</targy>
	<tanar kod="tan_03">
		<nev>Szabó Elemér</nev>
		<szak>Technika</szak>
	</tanar>
</iskola>
