=== Jorghy/QOHYCR_XMLgyak/QOHYCR_1008/ERkonvSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ERmodell">
		<xs:complexType>
			<xs:all>
				<xs:element name="A" type="aType" />
				<xs:element name="B" type="bType" />
				<xs:element name="C" type="cType" />
				<xs:element name="AtoB" type="atoBType" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="aType">
		<xs:all>
			<xs:element name="b" type="a_bType" />
			<xs:element name="c" />
		</xs:all>
		<xs:attribute name="a" />
	</xs:complexType>

	<xs:complexType name="a_bType">
		<xs:all>
			<xs:element name="x" />
			<xs:element name="y" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="bType">
		<xs:all>
			<xs:element name="b" type="b_bType" />
		</xs:all>
		<xs:attribute name="a" />
	</xs:complexType>

	<xs:complexType name="b_bType">
		<xs:all>
			<xs:element name="x" />
			<xs:element name="y" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="cType">
		<xs:all>
			<xs:element name="b" />
		</xs:all>
		<xs:attribute name="a" />
	</xs:complexType>

	<xs:complexType name="atoBType">
		<xs:all>
			<xs:element name="c" />
		</xs:all>
		<xs:attribute name="aID" />
		<xs:attribute name="bID" />
	</xs:complexType>


</xs:schema>

=== Jorghy/QOHYCR_XMLgyak/QOHYCR_1008/ERkonvSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<ERmodell xmlns:xsi="https://w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ERkonvSchema.xsd">
	
	<A a="aID">
		<b>
			<x></x>
			<y></y>
		</b>
		<b>
			<x></x>
			<y></y>
		</b>
		<c>
			<></> 
			<></> 
		</c>
	</A>
	
	<B a="bID">
		<b>
			<x></x>
			<y></y>
		</b>
	</B>
	
	<C a="cID">
		<b></b>
	</C>
	
	<AtoB aID="" bID="">
		<c></c>
	</AtoB>
</ERmodell>
